name = "cyberbuddha"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Custom domain
routes = [
  { pattern = "fo.hackthoughts.com", custom_domain = true }
]

[vars]
NETWORK = "base-sepolia"

# Static assets
[assets]
directory = "./public"
