name = "cyberbuddha"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Custom domain
routes = [
  { pattern = "fo.hackthoughts.com", custom_domain = true }
]

[vars]
NETWORK = "base-sepolia"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "cyberbuddha-wishes"
database_id = "72784d38-dfc3-44b7-a937-44a1100233b1"

# Static assets
[assets]
directory = "./public"
